/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedReaderRouteImport } from './routes/_authenticated/reader'
import { Route as ApiPublicRssRouteImport } from './routes/api/public/rss'
import { Route as ApiPublicHooksRefreshFeedsRouteImport } from './routes/api/public/hooks/refresh-feeds'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReaderRoute = AuthenticatedReaderRouteImport.update({
  id: '/reader',
  path: '/reader',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicRssRoute = ApiPublicRssRouteImport.update({
  id: '/api/public/rss',
  path: '/api/public/rss',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRefreshFeedsRoute =
  ApiPublicHooksRefreshFeedsRouteImport.update({
    id: '/api/public/hooks/refresh-feeds',
    path: '/api/public/hooks/refresh-feeds',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reader': typeof AuthenticatedReaderRoute
  '/api/public/rss': typeof ApiPublicRssRoute
  '/api/public/hooks/refresh-feeds': typeof ApiPublicHooksRefreshFeedsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reader': typeof AuthenticatedReaderRoute
  '/api/public/rss': typeof ApiPublicRssRoute
  '/api/public/hooks/refresh-feeds': typeof ApiPublicHooksRefreshFeedsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/reader': typeof AuthenticatedReaderRoute
  '/api/public/rss': typeof ApiPublicRssRoute
  '/api/public/hooks/refresh-feeds': typeof ApiPublicHooksRefreshFeedsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reader'
    | '/api/public/rss'
    | '/api/public/hooks/refresh-feeds'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reader'
    | '/api/public/rss'
    | '/api/public/hooks/refresh-feeds'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/reader'
    | '/api/public/rss'
    | '/api/public/hooks/refresh-feeds'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicRssRoute: typeof ApiPublicRssRoute
  ApiPublicHooksRefreshFeedsRoute: typeof ApiPublicHooksRefreshFeedsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reader': {
      id: '/_authenticated/reader'
      path: '/reader'
      fullPath: '/reader'
      preLoaderRoute: typeof AuthenticatedReaderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/rss': {
      id: '/api/public/rss'
      path: '/api/public/rss'
      fullPath: '/api/public/rss'
      preLoaderRoute: typeof ApiPublicRssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-feeds': {
      id: '/api/public/hooks/refresh-feeds'
      path: '/api/public/hooks/refresh-feeds'
      fullPath: '/api/public/hooks/refresh-feeds'
      preLoaderRoute: typeof ApiPublicHooksRefreshFeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedReaderRoute: typeof AuthenticatedReaderRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedReaderRoute: AuthenticatedReaderRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicRssRoute: ApiPublicRssRoute,
  ApiPublicHooksRefreshFeedsRoute: ApiPublicHooksRefreshFeedsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
